name: Mise à jour auto des articles IA

on:
  schedule:
    - cron: '0 */3 * * *'   # Toutes les 3 heures
  workflow_dispatch:         # Pour le lancer manuellement depuis GitHub

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          pip install -r requirements.txt

      - name: Lancer le scraping
        run: python main.py

      - name: Commit et push des articles
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add output/analyzed_articles_demo.json
          git commit -m "🔄 Mise à jour auto des articles IA"
          git push
